/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const useRoute: typeof import('uni-mini-router')['useRoute']
  const useRouter: typeof import('uni-mini-router')['useRouter']
}
